### ISSUE TITLE
L'installation ne marche pas avec un path différent

### ISSUE THREAD

**Issue by rgarrigue** [maniackcrudelis/rainloop_ynh#2]
Salut

J'ai eu l'idée de changer de path, /mail à la palce de /rainloop et il n'a pas trop apprécié

```
...
++ ls -1 /var/www/rainloop/data/
++ grep _data_
+ aleapath=
+ sudo cp ../conf/application.ini /var/www/rainloop/data//_default_/configs/
cp: impossible de créer le fichier standard « /var/www/rainloop/data//_default_/configs/ »: Aucun fichier ou dossier de ce type
+ sudo cp ../conf/disabled /var/www/rainloop/data//_default_/domains/
cp: impossible de créer le fichier standard « /var/www/rainloop/data//_default_/domains/ »: Aucun fichier ou dossier de ce type
+ sudo cp ../conf/domain.tld.ini /var/www/rainloop/data//_default_/domains/garrigue.re.ini
cp: impossible de créer le fichier standard « /var/www/rainloop/data//_default_/domains/garrigue.re.ini »: Aucun fichier ou dossier de ce type
+ sudo chown -R www-data: /var/www/rainloop
...
```

Sachant que l'installation fonctionne avec la valeur par défaut /rainloop

Rien de critique, mais pour info.

**Comment by maniackcrudelis** [comment]
Euh, je ne suis pas sûr de bien comprendre.
Le path demandé à l'installation est uniquement l'"adresse internet" de l'app.
L'erreur que tu as relevé est liée à l'absence du dossier créé par rainloop dans /data.

Cette erreur serait liée à la ligne:
curl -kL "https://$domain$path" > /dev/null

Retirer /dev/null pourrais nous en dire davantage sur ce qui se produit.

Il est plus probable que l'erreur viennent du package que de rainloop sur ce point.

**Comment by maniackcrudelis** [comment]
C'est peut-être le 2e location de la config nginx qui pose problème.
Ce qui impliquerait que le dossier dans /var/www doit avoir le même nom que le path.

Ce serait à tester.

**Comment by rgarrigue** [comment]
La seule chose que j'ai changé entre l'installation en échec et la réussie c'est le 2nd paramètre requis, sauf erreur de ma part c'est bien la path. Je comprend bien que ce soit bizarre. Je retesterai à l'occasion, vu que je bricole pas mal sur des VMs de test YunoHost, pour plus d'info.
11 septembre 2015 17:28 "Maniack Crudelis"  a écrit:
	Euh, je ne suis pas sûr de bien comprendre.
Le path demandé à l'installation est uniquement l'"adresse internet" de l'app.
L'erreur que tu as relevé est liée à l'absence du dossier créé par rainloop dans /data.

	Cette erreur serait liée à la ligne:
curl -kL "https://$domain$path" > /dev/null

	Retirer /dev/null pourrais nous en dire davantage sur ce qui se produit.

	Il est plus probable que l'erreur viennent du package que de rainloop sur ce point.

**Comment by maniackcrudelis** [comment]
C'était bien ça, la config nginx ne suivait pas correctement le changement du path.
C'est corrigé.

Merci d'avoir fait remonté ce bug ;)

**Comment by rgarrigue** [comment]
You're welcome! Merci pour Rainloop@Yunohost

11 septembre 2015 22:49 "Maniack Crudelis"  a écrit:
	C'était bien ça, la config nginx ne suivait pas correctement le changement du path.
C'est corrigé.

	Merci d'avoir fait remonté ce bug ;)
